version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    restart: always

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: postalservice
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
